### ISSUE TITLE
How to export GMSH model to Abaqus input file using Julia?

### ISSUE THREAD

**Issue by jayanthjayasimha** [JuliaFEM/Gmsh.jl#16]
gmsh.write(abs.inp)
I tried to do something like this but it doesnt seem to work.
I want to export the gmsh model that I generated using Julia into ".inp" file which i can later use in Abaqus.

**Comment by ahojukka5** [comment]
At the moment, we don't support writing ABAQUS input files - we only read them. And there are no plans to start doing so. If you want to contribute, we could create a new package like `AbaqusWriter.jl`.
