### ISSUE TITLE
revive this package

### ISSUE THREAD

**Issue by koehlerson** [JuliaFEM/Gmsh.jl#17]
Hey there,
I think the purpose of this package is extremely valuable and instead of attaching it to one specific FE framework we should (IMHO) just ship gmsh binaries and access to the `gmsh.jl`. If julia FE Frameworks want to support conversion than they should be able to make a PR with given conversion functions. What do you think about this?

**Comment by mipals** [comment]
Hi there,
I just wanted to say that I agree with you Maximilian. A revival of this package would definitely be appreciated as it has uses outside of just a FE framework.

**Comment by ahojukka5** [comment]
+1 from me also. Indeed this package would be useful for a lot of different FEM packages. The binaries are built in another repo (https://github.com/ahojukka5/GmshBuilder), and that time I did it according to the instructions provided by BinaryBuilder. I'm not sure if things have been changed from then?

**Comment by koehlerson** [comment]
I'm almost through the building process with the binarybuilder wizard. Afterwards I can check if something changed. Initially I asked because of this https://github.com/JuliaFEM/Gmsh.jl/issues/14
This sounded to me as if something went wrong with libgmsh.

**Comment by mipals** [comment]
Seems like you're already on top of things @koehlerson . My problems with the package was/is failures when building on `Julia nightly - windows-latest` (the error can be seen below)

> ERROR: Error building `Gmsh`: 
ERROR:` LoadError: Your platform ("x86_64-w64-mingw32", parsed as "x86_64-w64-mingw32-gcc8-cxx11") is not supported by this package!

Let me know if there is anything I can help with.

**Comment by koehlerson** [comment]
Ye already encountered this. I guess @ahojukka5 had the same problem with the binarybuilder.jl procedure and thus excluded the build. Cygwin build expects a different lib name. If we get a up to date building version, we can register it in yggdrasil and ask there for help w.r.t. cygwin builds on windows

**Comment by songhanzhang** [comment]
I have the same issue:

![Gmsh_err](https://user-images.githubusercontent.com/67284799/103262345-a9309480-49df-11eb-8597-bf991c03bffc.png)

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)    
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\Songhan\AppData\Local\atom\app-1.53.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6

**Comment by koehlerson** [comment]
this is expected because: https://github.com/ahojukka5/GmshBuilder/blob/master/build_tarballs.jl#L30-L33
windows is excluded from the supported platforms for now. 

I guess that it is excluded because the library won't be found under cygwin build, since its named differently under windows. In unix based stuff its named `libgmsh` while under windows it is `gmsh.dll` 

to fix this we need to pass a vector of possible options as done here: https://github.com/JuliaPackaging/Yggdrasil/blob/029965f93f1fe28fd9f3f6fe62cc4e04464dbfc1/P/PROJ/build_tarballs.jl#L54

**Comment by koehlerson** [comment]
Here is the PR to yggdrasil such that we have a `jll` for all platforms: https://github.com/JuliaPackaging/Yggdrasil/pull/2322

if it's merged we'll see a new repo in https://github.com/JuliaBinaryWrappers/ named gmsh

**Comment by koehlerson** [comment]
here is the new _jll repo https://github.com/JuliaBinaryWrappers/gmsh_jll.jl

**Comment by mipals** [comment]
Perfect! Is the idea to have `gmsh_jll.jl` provide the binaries and this package provide the `gmsh.jl` from the original `gmsh` library? Or is to only have the `gmsh_jll.jl` package?

**Comment by koehlerson** [comment]
So the idea of yggdrasil is that we provide there `build_tarball` scripts with a nice CI that checks for us if every platform can compile the binaries. If this is succesfull and merged into yggdrasil (which happily was done yesterday) another CI service is triggered which creates the `gmsh_jll.jl` repo that hosts everything to get the binaries working. So, in the end we say `using gmsh_jll` which exports the const `libgmsh` and use this instead of `lib` in the current gmsh dev api. If you want to, we can work here together:https://github.com/koehlerson/gmsh.jl

I just included `gmsh_jll` and copy pasted the gmsh api with slight changes. I think it would be nice if we could make it further julian by refactoring things such that the [blue style convention](https://github.com/invenia/BlueStyle) is fulfilled. I just tested the script in the README with the `gmsh_jll` and it works for me. If you use any thing other than arch, we can already test other binaries.

Edit: I chatted about this with more experienced users. It makes more sense to keep the api as it is and construct something higher level in a submodule or something similar

**Comment by fredrikekre** [comment]
Bump @ahojukka5 , there is now https://github.com/koehlerson/gmsh.jl and also https://github.com/WaveProp/GmshSDK and it would be good to combine efforts.

If you don't have time to work on this, would it be possible to give some more people access to this repository?

**Comment by geuzaine** [comment]
Out of curiosity, why don't you simply use the official binaries we ship in the binary Gmsh SDK? They are available for Linux (32 and 64 bit), Windows (32 and 64 bit) and macOS, are full-featured, and only depend on system libraries.

**Comment by koehlerson** [comment]
This is tried in https://github.com/WaveProp/GmshSDK, but fails for some versions and I don't know what the problem is (or how to fix it)

**Comment by geuzaine** [comment]
I'm clearly interested in understanding why/when it fails. Is there a bug report open somewhere? Don't hesitate to open an issue on the Gmsh gitlab https://gitlab.onelab.info/gmsh/gmsh/issues so we can track this.

**Comment by koehlerson** [comment]
https://github.com/WaveProp/GmshSDK/runs/1669535461?check_suite_focus=true

`gmsh.initialize()` fails with 

```julia
ERROR: LoadError: could not load symbol "gmshInitialize":
/opt/hostedtoolcache/julia/1.5.3/x64/bin/julia: undefined symbol: gmshInitialize
```

on Ubuntu in Julia v1.5 (which is the current release)

Other than that, [here is the bulding script](https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/gmsh/build_tarballs.jl) for `gmsh_jll.jl`, which  is the gmsh binary I've built and can be nicely included in any package with the full "julia linked library" support. How hard would it be to include OpenCASCADE?

**Comment by xue-cheng** [comment]
Might be a good idea to patch the official `gmsh.jl` in the building process and leave the low-level API in the `gmsh_jll.jl` package.

**Comment by geuzaine** [comment]
> https://github.com/WaveProp/GmshSDK/runs/1669535461?check_suite_focus=true
> 
> `gmsh.initialize()` fails with
> 
> ```julia
> ERROR: LoadError: could not load symbol "gmshInitialize":
> /opt/hostedtoolcache/julia/1.5.3/x64/bin/julia: undefined symbol: gmshInitialize
> ```
> 
> on Ubuntu in Julia v1.5 (which is the current release)
> 

So the dynamic library loader cannot find the C symbol `gmshInitialize`. Are you sure you installed the correct dynamic library and that Julia can find it?

**Comment by geuzaine** [comment]
> Might be a good idea to patch the official `gmsh.jl` in the building process and leave the low-level API in the `gmsh_jll.jl` package.

If possible please do not use `gmsh.jl` for something else than our official Gmsh Julia module. It will confuse users. If the official module needs patching don’t hesitate to create an issue in the Gmsh GitLab so we can investigate. 

PS: The latest development version of Gmsh defines snake case aliases for camelCase API functions in Julia and Python. I guess this should make the API feel less foreign to hardcore Julia users.

**Comment by koehlerson** [comment]
> > https://github.com/WaveProp/GmshSDK/runs/1669535461?check_suite_focus=true
> > `gmsh.initialize()` fails with
> > ```julia
> > ERROR: LoadError: could not load symbol "gmshInitialize":
> > /opt/hostedtoolcache/julia/1.5.3/x64/bin/julia: undefined symbol: gmshInitialize
> > ```
> > 
> > 
> > on Ubuntu in Julia v1.5 (which is the current release)
> 
> So the dynamic library loader cannot find the C symbol `gmshInitialize`. Are you sure you installed the correct dynamic library and that Julia can find it?

yes I know, but why would it works under Julia 1.6: https://github.com/WaveProp/GmshSDK/runs/1669535521?check_suite_focus=true. 

I'm not familiar with the artifact system if you do everything manually instead of using Yggdrasil to deploy `_jll.jl` repos as in `gmsh_jll.jl`. The script that created the artifact.toml in `GmshSDK` is https://github.com/WaveProp/GmshSDK/blob/main/scripts/generate_artifacts.jl. Looks solid to me, but again I'm neither the author nor have enough experience to make meaningful statements

**Comment by koehlerson** [comment]
@ahojukka5 thoughts about moving it into another org? maybe JuliaGeometry?

**Comment by stevengj** [comment]
> PS: The latest development version of Gmsh defines snake case aliases for camelCase API functions in Julia and Python. I guess this should make the API feel less foreign to hardcore Julia users.

It is more natural in Julia, but the downside is that the names no longer match the official API documentation, and the docstrings still refer to the camelCase API.  I suspect that it's not worth it.

**Comment by fredrikekre** [comment]
The camel case names still exist though.

Anyway, I think this package is successfully revived so closing.
