### ISSUE TITLE
troubles in running occ functions

### ISSUE THREAD

**Issue by avigliotti** [JuliaFEM/Gmsh.jl#20]
Hi,

I am having troubles using occ functions, for example I was trying to run the example t16 from here [t16.jl](https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/tutorial/julia/t16.jl) but I got this error

`import Gmsh: gmsh`
`gmsh.initialize()`
`gmsh.model.add("t16")`
`gmsh.model.occ.addBox(0,0,0, 1,1,1, 1)`

`gmshModelOccAddBox returned non-zero error code: 1`

could you please help me finding out what am I doing wrong here?

many thanks,
Andrea

**Comment by avigliotti** [comment]
i downloaded `libgmsh.so.4.8.4` from `https://gmsh.info/bin/` and replaced `libgmsh.so.4.4.1` in `eps/usr/lib`, that fixed the access to `occ` functions. 

However there is still something not working as if I try to open the gui `gmsh.fltk.run()` it crashes

Andrea

**Comment by koehlerson** [comment]
Works now with the new `gmsh_jll` version
