### ISSUE TITLE
Gmsh is outdated

### ISSUE THREAD

**Issue by perebalazs** [JuliaFEM/Gmsh.jl#29]
The current version of gmsh is 4.12.2, but the compatibility version in Gmsh.jl is 4.11.1. There are functions in gmsh which do not work with (the outdated) Gmsh.jl
Please update it.

Or remove the compatibility condition from Project.toml

**Comment by maltezfaria** [comment]
Is there a reason to have the compat entry of `gmsh_jll` down to a minor release? Why not simply set it to e.g. `4`?

**Comment by gpeairs** [comment]
Our experience has been that Gmsh is not always stable between minor and even patch releases. This recent update broke some operations in our test pipeline. We can set our Gmsh.jl compat to 0.3.0, so this is fine for now, but I think there are arguments for stricter compatibility requirements.

**Comment by maltezfaria** [comment]
Makes sense, thanks for the explanation.
