### ISSUE TITLE
Problems with libcairo on MacOS11

### ISSUE THREAD

**Issue by j-fu** [JuliaFEM/Gmsh.jl#33]
Hi, 
on MacOS11/Intel we have some problem to get Gmsh running. There seems to be some compatibility problem with libcairo. 

Things worked a while ago but now we get this:

https://github.com/j-fu/ExtendableGrids.jl/actions/runs/8983170213/job/24672339546?pr=45#step:6:465

Github actions with MacOS13 are ok.

This seems to be a problem similar to 

https://github.com/JuliaGraphics/Cairo.jl/issues/362

**Comment by j-fu** [comment]
@giordano: May be a Cairo compat update in the gmsh_jll build_tarballs could help here ?

**Comment by giordano** [comment]
Should be finally fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/8665 and https://github.com/JuliaPackaging/Yggdrasil/pull/8677, according to https://discourse.julialang.org/t/error-in-precompiling-harfbuzz-jll-and-gmsh-jll/114288/5

**Comment by j-fu** [comment]
Thanks a lot! FYI: it finally works also on the computer of my colleague who was stuck with this problem.
