### ISSUE TITLE
Directly download Gmsh SDK

### ISSUE THREAD

**Issue by shipengcheng1230** [JuliaFEM/Gmsh.jl#4]
Hi @ahojukka5, I just came across the slack fem channel and you mention the difficulty in compiling with BLAS.  I was wondering if we could just directly download the SDK to alleviate the pain of compiling? I did a similar thing at [here](https://github.com/shipengcheng1230/GmshTools.jl/blob/master/deps/build.jl) and it works so far fine. 

Best,
Pengcheng

**Comment by ahojukka5** [comment]
Well in principle, yes. I guess the questions are mainly that is everything necessary compiled to SDK, I mean shared library so that we can wrap, I guess. And the other question is the size of the zip file. If these are not the problem, then why not?

**Comment by shipengcheng1230** [comment]
From what I see, the SDK is pretty much complete, doing all the wrapper for us already. They never say in the doc that you'll miss something when using SDK instead of the official API. And the zip file is around 25 MB. Downloading from Gmsh website isn't as quick as here on Github, that's a downside but the downloading time is still reasonable.

**Comment by ahojukka5** [comment]
After looking for BinaryBuilder documentation I was able to add OpenBLAS dependency. I think I also need to add LAPACK. And the binary size is still bigger than 25 MB.

**Comment by shipengcheng1230** [comment]
Good to hear that. I wasn't successful a while ago trying BinaryBuilder for Gmsh. In addition to LAPACK, we might also need to add Open CASCADE since quite a few convenient geometry setups use that, which, in my experience, add more complexity to the building process. 

The only thing that isn't working well with the official SDK is [this issue](https://gitlab.onelab.info/gmsh/gmsh/issues/611) but will be solved upon the next version.

**Comment by ahojukka5** [comment]
I added environment variable `GMSH_USE_SDK` and when it's set to "true", SDK binaries are downloaded.
